"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


from functions.misc import is_pentagonal, is_hexagonal


def triangle(n):
    return int(n * (n + 1) / 2)


counter = 0
k = 1
while counter < 3:
    candidate = triangle(k)
    if is_pentagonal(candidate) and is_hexagonal(candidate):
        print(candidate)
        counter += 1
    k += 1
# 1533776805
