"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""
result = 0
prev_fib = 1
fib = 2
next_fib = 3
while result <= 4e6:
    if fib % 2 == 0:
        result += fib
    prev_fib = fib
    fib = next_fib
    next_fib = prev_fib + fib
print(result)
# 4613732
